# Generated by Django 3.0.5 on 2020-10-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='age',
            field=models.CharField(blank=True, default=20, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='bachelors',
            field=models.CharField(blank=True, default='None', max_length=200, null=True, verbose_name='Bachelors'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='disabilities',
            field=models.CharField(blank=True, default='None', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='government_id_type',
            field=models.CharField(choices=[('NIN', 'NIN'), ('PVC', 'Permanent Voters Card'), ('INTL', 'International Passport'), ('DRIV', "Drivers' License")], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='masters',
            field=models.CharField(blank=True, default='None', max_length=200, null=True, verbose_name='Masters'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nce',
            field=models.CharField(blank=True, default='None', max_length=100, null=True, verbose_name='College of Education'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phd',
            field=models.CharField(blank=True, default='None', max_length=100, null=True, verbose_name='Doctor of Philosophy(PhD)'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='post_grad',
            field=models.CharField(blank=True, default='None', max_length=100, null=True, verbose_name='Post Graduate Studies'),
        ),
    ]
