# Generated by Django 3.0.5 on 2020-10-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_auto_20201019_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='slug',
        ),
        migrations.AlterField(
            model_name='tutor',
            name='bank_account_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='government_id_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='government_id_type',
            field=models.CharField(blank=True, choices=[('NIN', 'NIN'), ('PVC', 'Permanent Voters Card'), ('INTL', 'International Passport'), ('DRIV', "Drivers' License")], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='yrs_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
