# Generated by Django 3.0.5 on 2020-10-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_auto_20201019_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
