# Generated by Django 3.0.5 on 2020-10-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_auto_20201019_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='age',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='bachelors',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bachelors'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='masters',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Masters'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='College of Education'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doctor of Philosophy(PhD)'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='post_grad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Post Graduate Studies'),
        ),
    ]
