# Generated by Django 3.0.5 on 2020-10-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_auto_20201025_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='dob',
        ),
        migrations.AlterField(
            model_name='tutor',
            name='bachelors',
            field=models.CharField(blank=True, default='None', max_length=200, null=True, verbose_name='Bachelors'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='masters',
            field=models.CharField(blank=True, default='None', max_length=200, null=True, verbose_name='Masters'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nce',
            field=models.CharField(blank=True, default='None', max_length=100, null=True, verbose_name='College of Education'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phd',
            field=models.CharField(blank=True, default='None', max_length=100, null=True, verbose_name='Doctor of Philosophy(PhD)'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='post_grad',
            field=models.CharField(blank=True, default='None', max_length=100, null=True, verbose_name='Post Graduate Studies'),
        ),
    ]
