# Generated by Django 3.0.5 on 2020-10-27 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0007_tutor_bvn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringplan',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major', to='tutors.Expertise'),
        ),
        migrations.AlterField(
            model_name='tutoringplan',
            name='minor1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minor1', to='tutors.Expertise'),
        ),
        migrations.AlterField(
            model_name='tutoringplan',
            name='minor2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minor2', to='tutors.Expertise'),
        ),
    ]
