# Generated by Django 3.0.5 on 2020-10-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0008_auto_20201027_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringplan',
            name='rate_per_hour',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
