# Generated by Django 3.0.5 on 2020-12-21 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0010_tutoringplan_desired_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tutoringplan',
            name='first_hour_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tutoringplan',
            name='fri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutoringplan',
            name='fri_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutoringplan',
            name='mon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutoringplan',
            name='mon_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutoringplan',
            name='sat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutoringplan',
            name='sat_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutoringplan',
            name='sun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutoringplan',
            name='sun_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutoringplan',
            name='thur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutoringplan',
            name='thur_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutoringplan',
            name='tue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutoringplan',
            name='tue_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutoringplan',
            name='wed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutoringplan',
            name='wed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutoringplan',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.Tutor'),
        ),
    ]
