# Generated by Django 3.0.5 on 2021-04-23 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0011_auto_20201221_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoringplan',
            name='desired_time',
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.Tutor')),
            ],
        ),
    ]
