# Generated by Django 3.1.1 on 2020-09-16 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200, verbose_name='Exact Address')),
                ('state', models.CharField(max_length=20, verbose_name='State')),
                ('local_govt', models.CharField(max_length=20, verbose_name='Local Government')),
                ('phone_number', models.CharField(max_length=14, verbose_name='Phone Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
