# Generated by Django 3.0.5 on 2020-09-28 22:46

from django.db import migrations, models
import django.db.models.deletion
import parents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=parents.models.upload_path)),
                ('title', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=14, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=200, verbose_name='Exact Address')),
                ('local_govt', models.CharField(max_length=20, verbose_name='Local Government')),
                ('state', models.CharField(max_length=20, verbose_name='State')),
                ('is_tutor', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(choices=[('online', 'Online Tutoring'), ('physical', 'Physical Tutoring'), ('both', 'Both')], default='online', max_length=10)),
                ('hour_per_day', models.PositiveIntegerField(verbose_name='Hours Per Day')),
                ('days_per_week', models.PositiveIntegerField(verbose_name='Days Per Week')),
                ('requested_duration', models.PositiveIntegerField(verbose_name='Weeks_Needed')),
                ('location_needed', models.CharField(max_length=200, verbose_name='Tutoring_Location')),
                ('description', models.TextField(max_length=1000)),
                ('purpose_of_cancellation', models.TextField(max_length=1000)),
                ('isAccepted', models.BooleanField(default=False)),
                ('inProgress', models.BooleanField(default=False)),
                ('isCompleted', models.BooleanField(default=False)),
                ('isCancelled', models.BooleanField(default=False)),
                ('isPaid', models.BooleanField(default=False)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_request', to='parents.ParentProfile')),
            ],
        ),
    ]
