# Generated by Django 3.0.5 on 2020-09-28 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorrequest',
            name='requested_tutorplan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_request', to='tutors.TutoringPlan'),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='subjects_requested',
            field=models.ManyToManyField(to='tutors.Expertise'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
