# Generated by Django 3.0.5 on 2020-10-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_auto_20200928_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Exact Address'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='local_govt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Local Government'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='purpose_of_cancellation',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
