# Generated by Django 3.0.5 on 2020-10-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_auto_20201010_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorrequest',
            old_name='purpose_of_cancellation',
            new_name='purpose_of_dispute',
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='inDispute',
            field=models.BooleanField(default=False),
        ),
    ]
