# Generated by Django 3.0.5 on 2020-12-21 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0011_auto_20201221_1131'),
        ('parents', '0007_auto_20201221_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorrequest',
            name='requested_tutorplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_request', to='tutors.TutoringPlan'),
        ),
    ]
