# Generated by Django 3.0.5 on 2020-12-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0008_auto_20201221_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorrequest',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
